### PR TITLE
Extract and rename Ribbons class.

### PR DESCRIPTION
**Pull request by pixelclef**
Ez,

I just got back from a PHP conference (I learned a metric ton). Inspired me to learn the fork pull model, to which I am a total and utter noob. I found this and followed it:
http://oss-watch.ac.uk/resources/pullrequest

Before I got too far, I wanted to see if - between the two of us - we could muddle our way through this collaboration model. If so, then I could make further changes and talk through them with you.

So, as described in the commit message, this pull requests extracts and renames the Ribbons class. The only testing I've done against it is to see if it loads and generates an image. It does.

### CODE REVIEW

**Comment by Ezriilc** [comment]
Pix,

Thanks!

I had to update the git before merging your changes, so then there were conflicts - that I think I fixed, and I'm not sure if I'm doing this right.

**Comment by pixelclef** [comment]
Does it still run after you finished?

**Comment by Ezriilc** [comment]
Yes!

**Comment by pixelclef** [comment]
I synced my fork and things look fine.

**Pull request merged**
